// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

namespace Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Domain.BloodWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hematocrit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hemoglobin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedBloodCellCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ResultsDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("WhiteBloodCellCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BloodWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
